### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by LoLei** [LoLei/razer-cli#18]
In addition to the [installation script](https://github.com/LoLei/razer-cli/blob/master/install.sh), it'd be great to have some form of packaged app available, e.g. on **PIP**, the AUR, or as a `deb`. If anyone is on a specific distro and wants to create a package for it, feel free to open a PR. 

Done:
* `pip` / [PyPI](https://pypi.org/project/razer-cli/) :heavy_check_mark:

**Comment by themayurkumbhar** [comment]
@LoLei 
It can be done using python pip repository.
You have to create the project on pip : [Pypi](https://pypi.org/) 
Then need to add the setup.py file in your code with it's installation steps. [Set up project](https://packaging.python.org/tutorials/packaging-projects/)
Let me know if you required info, will work further onto this.

**Comment by LoLei** [comment]
Thanks for reaching out @themayurkumbhar!  
Yes, I've actually started packaging for PyPI a while ago in [this branch](https://github.com/LoLei/razer-cli/tree/packaging), but then I implemented some other features and kinda left it stale.  
I already have it in the "Test" PyPI: https://test.pypi.org/project/razercli/, but I couldn't confirm that it was working. If you or anyone could test it from there and tell me if the installation is working, that'd be great, as it would tell me I was on the right path.  
Keep in mind that this is an outdated version of `razer-cli`.  
I'd still start over in a new branch I think, since I kinda messed around with various settings in this "Test" PyPI.

**Comment by themayurkumbhar** [comment]
Hello @LoLei 
I was able to install and run the cmd ` razercli --help`
please find the below snapshot.
however i needed to install 2 packages manually
1. `pip install openrazer`
2. `pip intall click`

it will better if these 2 packages are included as dependency in `setup.py`

Let me know your thoughts.

``` 
(venv) E:\Tech\python> razercli --help
Usage: razercli [OPTIONS] COMMAND [ARGS]...

  Razerkeyboard CLI

Options:
  --help  Show this message and exit.

Commands:
  off     Set the mode to static, default color ff00ff
  static  Set the mode to static, default color ff00ff

**Comment by LoLei** [comment]
This is very helpful, thanks @themayurkumbhar!  
I haven't thought about including the dependencies in `setup.py`, I'll do that.

The only thing that confuses me is the `click` dependency, as I don't remember using it, and the output of the help text is also vastly different from what it should be. In fact, it has never looked like this.  
Did you install it via `pip install -i https://test.pypi.org/simple/ razercli`? If I use this installation method, the help text looks like this:
```
$ razercli --help
usage: razercli [-h] [-e EFFECT] [-v] [-c COLOR [COLOR ...]] [-l] [-ll] [-a]
                [-d DEVICE [DEVICE ...]]

optional arguments:
  -h, --help            show this help message and exit
  -e EFFECT, --effect EFFECT
                        set effect
  -v, --verbose         increase output verbosity
  -c COLOR [COLOR ...], --color COLOR [COLOR ...]
                        choose color (default: X color1), use one argument for
                        hex, or three for base10 rgb
  -l, --list_devices    list available devices and their supported effects
  -ll, --list_devices_long
                        list available devices and all their capabilities
  -a, --automatic       try to find colors and set them to all devices without
                        user arguments, uses X or pywal colors
  -d DEVICE [DEVICE ...], --device DEVICE [DEVICE ...]
                        only affect these devices, same name as output of -l
```

**Comment by LoLei** [comment]
Anyway, I updated the package on TestPyPI: https://test.pypi.org/project/razer-cli/

**Comment by LoLei** [comment]
@themayurkumbhar I know what happened.

By issuing `pip install openrazer` you installed https://pypi.org/project/openrazer/ i.e. https://github.com/daniellawrence/openrazer-python, which is also a Python implementation of the openrazer-pylib, and which can also be run via the command `razercli -h`. This produces the same help text output for me.

So my package wasn't actually installed, is was the other one, confusingly named just `openrazer`, with the CLI command `razercli`.

**Comment by LoLei** [comment]
No it's available in the real PyPI: https://pypi.org/project/razer-cli

**Comment by themayurkumbhar** [comment]
@LoLei what pkg is exactly you released on pypi?
is it this : https://pypi.org/project/razer-cli
or 
is it still in test pypi?
which is : pip install -i https://test.pypi.org/simple/razercli

**Comment by themayurkumbhar** [comment]
i tried to install below one:

```
(venv) E:\Tech\python>pip install -i https://test.pypi.org/simple/ razer-cli
Looking in indexes: https://test.pypi.org/simple/
Collecting razer-cli Downloading https://test-files.pythonhosted.org/packages/42/14/d1048cacfd26e8ee978358c39065986c6d83c92f8807a9dad4eeaebaf398/razer_cli-0.9.1-py3-none-any.whl
Installing collected packages: razer-cli
Successfully installed razer-cli-0.9.1`

(venv) E:\Tech\python>razer-cli --help
Traceback (most recent call last):
  File "C:\Users\snow\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\snow\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Tech\python\myeven\Scripts\razer-cli.exe\__main__.py", line 5, in <module>
  File "e:\tech\python\myeven\lib\site-packages\razer_cli\razer_cli.py", line 12, in <module>
    from openrazer.client import DeviceManager
ModuleNotFoundError: No module named 'openrazer.client'
```

Let me know what things needs to be tested will try to install.

**Comment by LoLei** [comment]
@themayurkumbhar it's okay. You don't need to try again, but if you want to get it running you need to install openrazer via one of the packages of your distribution, not via pip. (See [here](https://openrazer.github.io/) under downloads.)

Also I just noticed that your file paths look like you're on Windows. Are you? If yes that's on me for not spotting this earlier. Because this tool **and** openrazer are for Linux only...

**Comment by themayurkumbhar** [comment]
Yes @LoLei ,  I was trying on Windows.
Cool let me know if you need any help 😊

**Comment by jdubz666** [comment]
Hey,

First of all thank you for putting this together! I've been waiting for a Linux Razer CLI for a long time....

I used

 pip install razer-cli 
and then
 pip3 install razer-cli

When I run razer-cli -h I get

Traceback (most recent call last):
  File "/usr/local/bin/razer-cli", line 11, in <module>
    load_entry_point('razer-cli==1.2', 'console_scripts', 'razer-cli')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named razer_cli.razer_cli

If it matters I'm on Debian and I already have OpenRazer for debian...

**Comment by LoLei** [comment]
@jdubz666 
Apparently your default Python is 2.7 (as seen in the error message: `/usr/lib/python2.7`). Likely the initial `pip install` run also used Python 2.7.
In any case, the module does of course not exist in the 2.7 lib directory.

Try uninstalling `razer-cli` and *only* installing via pip3:
```shell
pip uninstall razer-cli
pip3 uninstall razer-cli # maybe not needed
pip3 install razer-cli # maybe not needed
```

It should source the module from the Python 3 lib directory then. The environment is defined in the module (`#!/usr/bin/env python3`).

**Comment by jdubz666** [comment]
Thank you for the help! Much appreciated.

I uninstalled and only installed using pip3. I can not run it with the command "razer-cli". But I can run it with "/home/pi/.local/bin/razer-cli" and I get optional arguments. 

However when I run "/home/pi/.local/bin/razer-cli -a" I get the error...

Traceback (most recent call last):
  File "/home/pi/.local/bin/razer-cli", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/razer_cli/razer_cli.py", line 314, in main
    color = set_color(args.color)
  File "/home/pi/.local/lib/python3.7/site-packages/razer_cli/razer_cli.py", line 67, in set_color
    r, g, b = get_x_color()
  File "/home/pi/.local/lib/python3.7/site-packages/razer_cli/razer_cli.py", line 48, in get_x_color
    r, g, b = util.hex_to_decimal(rgb)
  File "/home/pi/.local/lib/python3.7/site-packages/razer_cli/util.py", line 6, in hex_to_decimal
    r = int(hex_color[0:2], 16)
ValueError: invalid literal for int() with base 16: ''

**Comment by LoLei** [comment]
@jdubz666 
You must add `/home/pi/.local/bin` to your `$PATH` environment variable to be able to run it with just `razer-cli`. (Append `export PATH=/home/pi/.local/bin:$PATH` to your `~/.bashrc` if you're using bash.)

As for the second issue, can you tell me what the output of `xrdb -query | grep "*color1:" | awk -F '#' '{print $2}'` is? It should output the hex color values of the colors stored in  Xresources, which is used with the `-a` flag. Have you tried the `-c` flag to set a color manually? E.g. `razer-cli -c ff00ff`. Also, `xrdb` needs to be installed manually in some cases, if you haven't, it's a [dependency](https://github.com/LoLei/razer-cli#dependencies) for `-a`.

**Comment by LoLei** [comment]
Closing this issue as it has been derailed a bit. 
@jdubz666 if you still need help feel free to open a new issue.
