### ISSUE TITLE
No module named 'openrazer.client'

### ISSUE THREAD

**Issue by katacarbix** [LoLei/razer-cli#24]
When running from pip package:

```
Traceback (most recent call last):
  File "/home/reese/.local/bin/razercli", line 5, in <module>
    from razercli.razercli import main
  File "/home/reese/.local/lib/python3.8/site-packages/razercli/razercli.py", line 12, in <module>
    from openrazer.client import DeviceManager
ModuleNotFoundError: No module named 'openrazer.client'
```

When running from latest source:

```
Traceback (most recent call last):
  File "razer_cli/razer_cli.py", line 12, in <module>
    from openrazer.client import DeviceManager
ModuleNotFoundError: No module named 'openrazer.client'
```

Note: I had to manually install openrazer because it threw `No module named 'openrazer'` before.

Python version: 3.8.2    
pip version: 20.0.2

**Comment by LoLei** [comment]
Which `openrazer` did you install? It must not be the one from pip, it has to be [this one](https://github.com/openrazer/openrazer#installation).

This is [mentioned in the Readme](https://github.com/LoLei/razer-cli#dependencies).

**Comment by katacarbix** [comment]
Ah, that solved it. I had them installed concurrently, not knowing it caused a conflict. Thanks!
