### ISSUE TITLE
Add Support for Polling Rate (with patch)

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [LoLei/razer-cli#35]
[razer_cli.zip](https://github.com/LoLei/razer-cli/files/5826659/razer_cli.zip)
Change Log:

- [New] Set Polling Rate (`razer-cli --poll 125|500|1000`)
- [New] Read Polling Rate (`razer-cli --poll print`)
- [New] Show Polling Rate in device list (`razer-cli -l`)
- [New] Print DPI (`razer-cli --dpi print`)
- [Change] Support different X/Y DPI settings
- [Fix] Do not mess with RGB stuff if it is not being touched (minor performance upgrade)

Sorry the patch includes other stuff, i do not bother with version control

**Comment by LoLei** [comment]
I'll take a look at it and put the changes in if everything is working, thanks!

**Comment by LoLei** [comment]
Done in #37
