### ISSUE TITLE
-ll and -llh possible at once

### ISSUE THREAD

**Issue by LoLei** [LoLei/razer-cli#39]
https://github.com/LoLei/razer-cli/pull/37#issuecomment-763001176

Currently it's possible to do `-ll` and `-llh` at the same time:
```
razer-cli -ll -llh
```

Which outputs both the JSON format and the human readbale format.

Maybe some [argparse](https://docs.python.org/3/library/argparse.html) options could be used to make this flag better. E.g. make it so it's actually the same flag but `h` adds an additional option to it.

**Comment by GM-Script-Writer-62850** [comment]
https://github.com/LoLei/razer-cli/blob/master/razer_cli/razer_cli.py#L123
Before:
`if (args.list_devices_long_human):`
After:
`elif (args.list_devices_long_human):`

but should we? does it hurt anyone? does it help anyone? does it matter? is it a feature or a bug? I asked the AI and I got 42...
