### ISSUE TITLE
[Patch] Make use of settings file and update color input to support many colors at once

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [LoLei/razer-cli#48]
[settings+color_patch.zip](https://github.com/LoLei/razer-cli/files/5871199/settings%2Bcolor_patch.zip)
Looked like the settings file was a feature made for future use, i made a `--restore` option that will spit out commands to apply what is found in the file, also added new features to the settings file, also made the `--color` option allow multi color input

```
~/.local/bin/razer-cli --restore
Feature incomplete, here are the command(s) to restore the settings:
    razer-cli -d 'Razer DeathAdder Elite' -c 0 0 0 17 17 17 255 255 255 --dpi 1100 --poll 1000 -e static -b logo 0 scroll 0 generic 0 left 0 right 0
```
at present only the 1st color is used for anything, but it gives you the framework to get fancy with color input, not sure if there is a limit to how many colors you can input, maybe you will hit a max arguments count or something

**Comment by GM-Script-Writer-62850** [comment]
I do have a follow up patch to add support for color zones
At this point that patch allows you to set a different color for each zone so left, right, logo, scroll_wheel, and overall can all be different colors, at present it only applies to static, so i have that ready to go, should server as example usage for you to expand upon

**Comment by LoLei** [comment]
I had a few issues when testing this, a few of which were fixed when deleting my old settings file (`.cache/razer-cli/razer-cli-settings.json`), the other fixes I added to the pull request: https://github.com/LoLei/razer-cli/pull/49

In the future it would great if you could add test cases as well which test these new functions. Similar to how it's done [here](https://github.com/LoLei/razer-cli/tree/master/tests) already. In this case you could for example add a settings.json file and check if the correct `--restore` output is created.

These tests are also run automatically when a pull request is submitted.

**Comment by GM-Script-Writer-62850** [comment]
The settings file would get fixed as soon as you use anything other than `--restore` as far as i could tell  the file as not used for anything before this patch was made, so it is not like it was useful for anything other than reading in a text editor (or `cat`)
