### ISSUE TITLE
This can be cleaner since get_x_color is better [default_color in set_effect_to_device]

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [LoLei/razer-cli#55]
We can delete this from here
https://github.com/LoLei/razer-cli/blob/master/razer_cli/razer_cli.py#L399-L400
and change this:
https://github.com/LoLei/razer-cli/blob/master/razer_cli/razer_cli.py#L447
to `color = [util.get_x_color(args.verbose)]`
this drops 2 lines and changes one

**Comment by LoLei** [comment]
Added it in https://github.com/LoLei/razer-cli/commit/1aab20c39a278630cedeac4918cd0ff86d91aae4
