### ISSUE TITLE
Effect is supported by device but not yet implemented - Spectrum

### ISSUE THREAD

**Issue by ohaessler** [LoLei/razer-cli#56]
it would be great to get the spectrum effect support added to the tool

razer-cli -l
Found 2 Razer devices
Razer Ornata Chroma:
   type: keyboard
   brightness: 75.0
   serial: UNKWN000000002744
   firmware version: v1.0
   driver version: 2.9.0
   effects: ['breath_dual', 'breath_random', 'breath_single', 'reactive', 'ripple', 'ripple_random', 'spectrum', 'starlight_dual', 'starlight_random', 'static', 'wave']
Razer Naga Hex V2:
   type: mouse
   DPI: (800, 800)
   max DPI: 16000
   polling rate: 500
   brightness: 75.0
   brightness (logo): 75.0
   brightness (wheel): 75.0
   serial: UNKWN000000003776
   firmware version: v1.0
   driver version: 2.9.0
   effects: ['breath_dual', 'breath_random', 'breath_single', 'logo_breath_single', 'logo_reactive', 'logo_static', 'reactive', 'scroll_breath_single', 'scroll_reactive', 'scroll_static', 'spectrum', 'static']

razer-cli --sync -e spectrum
creating path and file
Adding new settings entry
Effect is supported by device but not yet implemented.
Consider opening a PR:
https://github.com/LoLei/razer-x-color/pulls
Adding new settings entry
Effect is supported by device but not yet implemented.
Consider opening a PR:
https://github.com/LoLei/razer-x-color/pulls

Thanks
Oliver

**Comment by LoLei** [comment]
This has been fixed in a recent patch, but a new version has not yet been released to PyPI. I'll do so in a short while. If you want it earlier, you can check out this repo, and install the content using `pip install . --user` inside the repo.

**Comment by ohaessler** [comment]
Hi LoLei .. thanks for the quick release. It looks like the python version requirement has changed, and so I can no longer use the tool on Red hat Enterprise Linux 8:

ERROR: Package 'razer-cli' requires a different Python: 3.6.8 not in '>=3.7'

**Comment by LoLei** [comment]
I'll try lowering the version requirement. 3.6 should be possible.

**Comment by LoLei** [comment]
@ohaessler I decreased the minimum version in a branch. Before I release this, could you please test it in that branch to see if it works?

```
pip uninstall razer-cli
git clone https://github.com/LoLei/razer-cli.git
cd razer-cli
git checkout decrease-version
pip install . --user
```

**Comment by ohaessler** [comment]
I am getting this error:

`Successfully installed razer-cli-2.0.0
[ohaessle@ohaessle razer-cli (decrease-version)]$ razer-cli --sync -e spectrum
Traceback (most recent call last):
  File "/home/ohaessle/.local/bin/razer-cli", line 33, in <module>
    sys.exit(load_entry_point('razer-cli==2.0.0', 'console_scripts', 'razer-cli')())
  File "/home/ohaessle/.local/bin/razer-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/ohaessle/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ohaessle/.local/lib/python3.6/site-packages/razer_cli/razer_cli/main.py", line 16, in <module>
    from razer_cli.razer_cli.rc import RazerCli
  File "/home/ohaessle/.local/lib/python3.6/site-packages/razer_cli/razer_cli/rc.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined`

**Comment by LoLei** [comment]
This is what I was afraid of. Strange that the [pipeline](https://github.com/LoLei/razer-cli/actions/runs/569283028) runs through but I guess that one uses 3.6.12. I'll see if I can find a workaround. You can try to edit the code yourself btw and see if you can find a solution. Just install it with `pip install -e . --user` and code changes will be reflected in the installed script automatically.

**Comment by ohaessler** [comment]
So, I gave it a try, and the below patch fixes the error for me on RHEL 8 and the sync feature is working now with my keyboard and mouse.

https://gist.github.com/ohaessler/57c83a7d64268da40f31bccef2dbbced

**Comment by LoLei** [comment]
You can open a pull request if you want, that replaces all `from __future__ import annotations` calls with this change. If not I'll add it myself.
