### ISSUE TITLE
Drop sys from argument_parser.py (optimization patch)

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [LoLei/razer-cli#57]
Refracting patch eliminates need for `import sys` in this file, if you really want to use `sys.exit(1)` you can do so in place of `return False` in `razer_cli.py`
```
diff -Naur --exclude __pycache__ razer-cli-master/razer_cli/razer_cli/parsing/argument_parser.py razer-cli/razer_cli/parsing/argument_parser.py
--- razer-cli-master/razer_cli/razer_cli/parsing/argument_parser.py	2021-02-12 09:36:43.000000000 -0500
+++ razer-cli/razer_cli/parsing/argument_parser.py	2021-02-12 10:45:54.975282604 -0500
@@ -1,5 +1,4 @@
 import argparse
-import sys
 from typing import List
 
 
@@ -83,6 +82,6 @@
 
     if len(input_args) < 1:
         parser.print_help()
-        sys.exit(1)
+        return False
 
     return parser.parse_args(input_args)
diff -Naur --exclude __pycache__ razer-cli-master/razer_cli/razer_cli/razer_cli.py razer-cli/razer_cli/razer_cli.py
--- razer-cli-master/razer_cli/razer_cli/razer_cli.py	2021-02-12 09:36:43.000000000 -0500
+++ razer-cli/razer_cli/razer_cli.py	2021-02-12 10:41:45.911775225 -0500
@@ -89,6 +89,8 @@
     """ Main entry point of the app """
     global args
     args = read_args(sys.argv[1:])
+    if not args:
+        return False
 
     if args.manual is not None:
         return util.print_manual(args.manual)
```

**Comment by LoLei** [comment]
I implore you to open a pull request with this change.

**Comment by GM-Script-Writer-62850** [comment]
in the interest of science i tried only importing stuff when it is relevant from the `main` function and ran some performance testing
[razer_cli.py.zip](https://github.com/LoLei/razer-cli/files/5976061/razer_cli.py.zip)

![Screenshot_2021-02-13_11-49-29](https://user-images.githubusercontent.com/564653/107855623-8b818800-6df1-11eb-8a19-fb0f87c3201a.png)
* before includes the above patch
* these numbers are the realtime execution time in seconds

**Comment by LoLei** [comment]
So the difference is about 0.001 to 0.002 seconds?

**Comment by GM-Script-Writer-62850** [comment]
and i am not comfortable saying that is outside the margin of error

even my very light simple script takes .1558s on average (10 samples)
```
~$ cat .local/bin/getRazerDPI_genmon.py
#!/usr/bin/env python3
from openrazer.client import DeviceManager
dev=DeviceManager().devices[0]
dpi=dev.dpi
if dpi[0] == dpi[1]:
	if dpi[0] == 1800:
		dev.dpi=(900,900)
	elif dpi[0] == 4500:
		dev.dpi=(1000,1000)
	elif dpi[0] == 9000:
		dev.dpi=(1100,1100)
	elif dpi[0] == 16000:
		dev.dpi=(1200,1200)
	out=str(dev.dpi[0])
else:
	out=str(dpi[0])+','+str(dpi[1])
print("<txt>"+out,"DPI</txt><tool>"+dev.name+"</tool>")

```
i use this with the xfce4-genmon plugin for the xfce4-panel as it is better than calling this tool several times via a shell script
if you missed it i attached the modded file i did that testing with above
