### ISSUE TITLE
Reactive effect for Razer Mousepad (Firefly) doesn't work

### ISSUE THREAD

**Issue by GitGangGuy** [LoLei/razer-cli#60]
The Windows Razer app (which I used to use back when I was soy) makes the mousepad flash reactively when I click my mouse. However, even though the 'reactive' effect appears to be supported by this program for my mousepad, it won't do anything - my mousepad stays dark. Is this a known issue?

**Comment by LoLei** [comment]
Hi, thanks for reporting. I didn't even know a Razer mousepad was a thing, that's cool.

Can you show me the output of commands along the lines of:
```bash
$ razer-cli -ll
# and
$ razer-cli --verbose -e reactive # or whatever command you're running to achieve the desired effect
```

**Comment by GitGangGuy** [comment]
```bash
$ razer-cli -ll
Found 3 Razer device(s)
[...]
Razer Firefly:
   type: mousemat
   generic zone:
      effects available:
         breath_dual
         breath_random
         breath_single
         none
         reactive
         spectrum
         static
         wave
         multicolor
   serial: [...]
   firmware version: v1.0
   driver version: 2.9.0
   supported capabilities:
      name
      type
      firmware_version
      serial
      brightness
      lighting
      lighting_breath_single
      lighting_breath_dual
      lighting_breath_random
      lighting_wave
      lighting_reactive
      lighting_none
      lighting_spectrum
      lighting_static
      lighting_led_matrix
```
and
```bash
$ razer-cli --sync -a -e reactive -v # or razer-cli -a -e reactive -v etc.
Using [76, 18, 183] for X Color
[...]
Setting effects for Razer Firefly:
   generic:
      Setting reactive to: 76 18 183 @ timing level 2
   logo:
      logo is not supported
   scroll_wheel:
      scroll_wheel is not supported
   left:
      left is not supported
   right:
      right is not supported
   backlight:
      backlight is not supported
```
The effect output is the same as with my Razer keyboard, only the timing level differs (4 vs 2).
The mousepad stays black no matter what I do.
The issue you referenced is about the [Razer Firefly V2](https://www.razer.com/gaming-mouse-mats/razer-firefly-v2/RZ02-03020100-R3U1) mousemat, however I own the first version ([Razer Firefly Chroma](https://www.amazon.com/Razer-Firefly-Chroma-Gaming-Mousepad/dp/B00Y4S5KPY)).

**Comment by LoLei** [comment]
Thanks!

Hmm… It looks like the effect is applied:
>Setting reactive to: 76 18 183 @ timing level 2

Do any of the more basic effects work or even just static color? E.g. `razer-cli -v -c ff0000`. I assume no.

Could you also try an older version of razer-cli? There's been some major changes recently which may have broken something. Try version [1.3.2](https://pypi.org/project/razer-cli/1.3.2/).

It's hard for me to look into this as I do not have the hardware. You could however debug the code yourself.
You can uninstall razer-cli, clone the repo and execute `pip install -e . --user` in it. Then you can edit the code and the script will have your changes automatically. You could add a few debug print statements or even use a debugger (e.g. Pycharm) to find out what's different to your other devices. (Presumably they work?) You may have to start it via a [test case](https://github.com/LoLei/razer-cli/tree/master/razer_cli/tests) then, to attach the debugger to the process, as opposed to running the script via the command line.

**Comment by GitGangGuy** [comment]
@LoLei 
> Do any of the more basic effects work or even just static color? E.g. `razer-cli -v -c ff0000`. I assume no.

All the other effects work, only reactive doesn't. I'm just using a different effect now, sorry but I don't have the time to diagnose the issue.
Thank you for looking into it!

**Comment by LoLei** [comment]
If it's only reactive that doesn't work that's strange indeed. If you ever have time in the future to look into this I'd appreciate it!
